### ISSUE TITLE
shed_tools install fails with `KeyError: 'tool_shed_url'`

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/ephemeris#124]
After installing from master:

```
pip install https://github.com/galaxyproject/ephemeris/archive/master.zip
```

calling:

```
shed-tools install -t tools.yaml -g <instance> -a <key>
....
lib/python2.7/site-packages/ephemeris/get_tool_list_from_galaxy.py", line 186, in merge_repository_changeset_revisions
    repo_key = repo_key_template.format(**repo)
KeyError: 'tool_shed_url'
```

The yaml file records look like this:
```
tools:
- name: cutadapt
  owner: lparsons
  tool_panel_section_label: RNA-Seq
  tool_shed_url: "https://toolshed.g2.bx.psu.edu/"
  revisions:
  - 660cffd8d92a
- name: data_manager_fetch_genome_dbkeys_all_fasta
  owner: devteam
  tool_panel_section_label: RNA-Seq
  tool_shed_url: "https://toolshed.g2.bx.psu.edu/"
  revisions:
  - b1bc53e9bbc5
```

This works when using a virtualenv with ephemeris installed through `pip install ephemeris`.
