### ISSUE TITLE
new data-manager manager script

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/ephemeris#29]
I'm working currently on a data-manager manager script to pre-load Galaxy training instances.
Current definition looks like that:

```
# configuration for fetch and index genomes

data_managers:
    - id: toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/data_manager_fetch_genome_all_fasta_dbkey/0.0.2
      params:
        - 'dbkey': '{{ item }}'
        - 'reference_source|reference_source_selector': 'ucsc'
        - 'reference_source|requested_dbkey': '{{ item }}'
      items:
        - dm3
        - mm9

    - id: toolshed.g2.bx.psu.edu/repos/devteam/data_manager_bowtie2_index_builder/bowtie2_index_builder_data_manager/2.2.6
      params:
        - 'all_fasta_source': '{{ item }}'
      items:
        - dm3
        - mm9
```
